name: Build on Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Boost
      run: |
        cd C:\
        curl -LsO https://boostorg.jfrog.io/artifactory/main/beta/1.78.0.beta1/source/boost_1_78_0_b1.zip
        unzip -q boost_1_78_0_b1.zip
        cd boost_1_78_0
        .\bootstrap.bat
    - name: Setup environment
      run: |
        echo 'set BOOST_ROOT=C:\boost_1_78_0' > env.bat
        echo 'set ARCH=x64' >> env.bat
        echo 'set BJAM_TOOLSET=msvc-14.2' >> env.bat
        echo 'set CMAKE_GENERATOR="Visual Studio 17 2022"' >> env.bat
        echo 'set PLATFORM_TOOLSET=v142' >> env.bat
    - name: Build
      run: |
        .\build.bat boost
        .\build.bat thirdparty
        .\build.bat librime
        .\build.bat test
    - name: Test
      run: |
        copy /y dist\lib\rime.dll build\test
        cd build\test
        .\Release\rime_test.exe
